spring:
  # 注册中心
  cloud:
    consul:
      discovery:
        register: true
        enabled: true
        prefer-ip-address: true
        service-name: ${spring.application.name}
        health-check-critical-timeout: 5m
        health-check-interval: 15s
        tags: profile=${spring.profiles.active}
        instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}:${random.int[1000,9999]}
        health-check-url: http://${spring.cloud.client.ip-address}:${server.port}/actuator/health
    httpclientfactories.ok.enabled: false
  main:
    allow-bean-definition-overriding: true


  # 数数库
  datasource:
    host: 192.168.0.210
    port: 3306
    username: uptang
    password: uptang408*


  # 缓存
  redis:
    database: 0
    timeout: 3000
    port: 52199
    host: xfs_redis.weave.local
    password: uptang123
    lettuce:
      pool:
        max-idle: 10
        min-idle: 1
        max-active: 10
        max-wait: 1000

  # Kafka, 可以是多个地址
  kafka:
    bootstrap-servers: svc_kafka.weave.local:9092

    # 生产者
    producer:
      client-id: ${spring.application.name}_${random.int[1000,9999]}
      acks: all
      retries: 1
      batch-size: 16KB
      buffer-memory: 32MB
      compression-type: gzip
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      # transaction-id-prefix: @project.name@
      properties:
        partitioner.class: org.apache.kafka.clients.producer.internals.DefaultPartitioner
        enable.idempotence: true

    # 消费者
    consumer:
      group-id: paper-image-process
      enable-auto-commit: true
      auto-commit-interval: 100
      auto-offset-reset: latest
      fetch-min-size: 1
      heartbeat-interval: 3000ms
      max-poll-records: 50
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

    # 并发监听
    listener:
      type: batch
      concurrency: 5


# feign 配置
feign:
  client:
    config:
      default:
        connectTimeout: 10000
        readTimeout: 10000
  compression:
    request:
      enabled: true
    response:
      enabled: true

# 华为云对象存储
obs:
  access-key: U4NQADBPTUUDKFVXBRAJ
  secret-key: iMdARdabBowyDtNtMHgETtIZtEot9HmT4WvRPg8z
  end-point: https://obs.cn-north-1.myhuaweicloud.com
  bucket-name: uptang-cloud-dev
  domain: https://uptang-cloud-dev.obs.cn-north-1.myhuaweicloud.com
  crop-mode: both # 横拼:horizontally, 竖拼:vertically, 两者:both

logging:
  path: ./app-logs
  level:
    root: INFO
    api: DEBUG
    service: DEBUG
    repository: DEBUG